version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    expose: 
      - 5432
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_DB=rails_url_development
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes: 
      - ./tmp/data/postgresql:/var/lib/postgresql/data