version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    expose: 
      - 5432
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_DB=rails_url_development
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes: 
      - ./tmp/data/postgresql:/var/lib/postgresql/data
  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: rails_url_development
      DATABASE_USERNAME: username
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      RAILS_ENV: development
    volumes:
      - .:/myapp